apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: clean
      image: alpine:3
      script: |
        #!/bin/sh
        echo "Limpiando el workspace..."
        rm -rf $(workspaces.source.path)/*