apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npminstall
spec:
  steps:
    - name: install
      image: node:20-buster-slim
      workingDir: /workspace/source
      script: |
        #!/bin/bash
        npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  steps:
    - name: test
      image: node:20-buster-slim
      workingDir: /workspace/source
      script: |
        #!/bin/bash
        npx jasmine